import type { Dictionary } from "@/lib/i18n/locale"

export const SUPPORT = {
  pageTitle: { ar: "الدعم", en: "Support" },
  helpTitle: { ar: "مركز المساعدة", en: "Help center" },

  viewOpen: { ar: "بانتظار ردّنا", en: "Needs reply" },
  viewMine: { ar: "المُسندة إليّ", en: "Mine" },
  viewUnassigned: { ar: "غير مُسندة", en: "Unassigned" },
  viewWaiting: { ar: "بانتظار العميل", en: "Waiting" },
  viewResolved: { ar: "مُغلقة", en: "Resolved" },
  viewAll: { ar: "الكل", en: "All" },
  search: { ar: "بحث بالاسم أو البريد أو النص…", en: "Search name, email or text…" },
  loadMore: { ar: "المزيد", en: "Load more" },
  loadOlder: { ar: "رسائل أقدم", en: "Older messages" },
  empty: { ar: "لا محادثات هنا.", en: "No conversations here." },
  pickThread: { ar: "اختر محادثة من القائمة.", en: "Pick a conversation from the list." },
  notFound: { ar: "المحادثة غير موجودة.", en: "Conversation not found." },

  statusOpen: { ar: "بانتظار ردّنا", en: "Needs reply" },
  statusWaiting: { ar: "بانتظار العميل", en: "Waiting on them" },
  statusResolved: { ar: "مُغلقة", en: "Resolved" },

  topicAccount: { ar: "الحساب", en: "Account" },
  topicKyc: { ar: "التحقق من الهوية", en: "Identity check" },
  topicBilling: { ar: "الاشتراك", en: "Billing" },
  topicRecovery: { ar: "الاسترداد", en: "Recovery" },
  topicClaim: { ar: "بلاغ وفاة", en: "Death report" },
  topicDelivery: { ar: "تسليم", en: "Delivery" },
  topicOther: { ar: "أخرى", en: "Other" },

  surfaceMobile: { ar: "التطبيق", en: "App" },
  surfaceWeb: { ar: "الموقع", en: "Web" },

  guest: { ar: "زائر", en: "Guest" },
  guestUnverified: {
    ar: "زائر — الاسم والبريد كما كتبهما، غير موثّقين. لا تؤكّد له وجود حساب أو خزنة.",
    en: "Guest — name and email as typed, unverified. Never confirm to them that an account or vault exists.",
  },
  account: { ar: "حساب", en: "Account" },
  openAccount: { ar: "فتح الحساب", en: "Open account" },
  openReport: { ar: "فتح البلاغ", en: "Open report" },
  openDeliveries: { ar: "فتح التسليمات", en: "Open deliveries" },
  requester: { ar: "صاحب المحادثة", en: "Requester" },
  context: { ar: "مرتبطة بـ", en: "About" },
  assignee: { ar: "المسؤول", en: "Assignee" },
  unassigned: { ar: "لا أحد", en: "Nobody" },
  takeIt: { ar: "استلمها", en: "Take it" },
  release: { ar: "تخلَّ عنها", en: "Let go" },
  resolve: { ar: "إغلاق", en: "Resolve" },
  reopen: { ar: "إعادة فتح", en: "Reopen" },
  opened: { ar: "بدأت {date}", en: "Started {date}" },
  filesPurged: {
    ar: "حُذفت مرفقات هذه المحادثة بعد انتهاء مدة الاحتفاظ.",
    en: "This conversation's files were deleted when the retention period ended.",
  },

  staff: { ar: "فريق وصيّة", en: "Wassiya team" },
  you: { ar: "العميل", en: "Requester" },
  reply: { ar: "ردّ", en: "Reply" },
  replyPlaceholder: {
    ar: "اكتب ردّاً — يصل العميل فوراً.",
    en: "Write a reply — the requester sees it immediately.",
  },
  send: { ar: "إرسال", en: "Send" },
  attach: { ar: "إرفاق", en: "Attach" },
  notes: { ar: "ملاحظات داخلية", en: "Internal notes" },
  notesHint: {
    ar: "للفريق فقط — لا يراها العميل أبداً.",
    en: "Team only — the requester never sees these.",
  },
  notePlaceholder: { ar: "أضف ملاحظة…", en: "Add a note…" },
  addNote: { ar: "إضافة", en: "Add" },
  noNotes: { ar: "لا ملاحظات.", en: "No notes." },
  guardrail: {
    ar: "لا تطلب أبداً وثيقة الاسترداد أو ورقة الوصي أو رموزهما أو رقم الهوية. الدعم لا يفتح الخزنة ولا يستردّها.",
    en: "Never ask for the recovery sheet, an executor sheet, their codes or an ID number. Support cannot open or recover a vault.",
  },

  refusedRecovery: {
    ar: "يبدو أن الرسالة تحتوي رمز وثيقة استرداد أو ورقة وصي — لم تُرسل.",
    en: "That message looks like it contains a recovery or executor sheet code — not sent.",
  },
  refusedAttachment: {
    ar: "المرفق غير مقبول: صور أو PDF حتى ١٠ م.ب، خمسة كحدّ أقصى.",
    en: "Attachment refused: images or PDF up to 10 MB, five at most.",
  },
  refusedTooLong: { ar: "الرسالة أطول من المسموح.", en: "The message is too long." },
  failed: { ar: "تعذّر ذلك.", en: "That did not work." },

  // Help center
  newArticle: { ar: "مقال جديد", en: "New article" },
  editArticle: { ar: "تحرير المقال", en: "Edit article" },
  slug: { ar: "المعرّف", en: "Slug" },
  audience: { ar: "الجمهور", en: "Audience" },
  audienceOwner: { ar: "المالكون", en: "Owners" },
  audienceExecutor: { ar: "الأوصياء", en: "Executors" },
  audienceReporter: { ar: "المُبلِّغون", en: "Reporters" },
  audienceAll: { ar: "الجميع", en: "Everyone" },
  order: { ar: "الترتيب", en: "Order" },
  published: { ar: "منشور", en: "Published" },
  draft: { ar: "مسودّة", en: "Draft" },
  titleAr: { ar: "العنوان (عربي)", en: "Title (Arabic)" },
  titleEn: { ar: "العنوان (إنجليزي)", en: "Title (English)" },
  bodyAr: { ar: "النص (عربي)", en: "Body (Arabic)" },
  bodyEn: { ar: "النص (إنجليزي)", en: "Body (English)" },
  articleRule: {
    ar: "لا تذكر حدود الخطط ولا الأسعار — تتغيّر دون نشر. أحِل إلى شاشة الخطة.",
    en: "Never state plan limits or prices — they change without a deploy. Point to the plan screen.",
  },
  save: { ar: "حفظ", en: "Save" },
  delete: { ar: "حذف", en: "Delete" },
  deleteTitle: { ar: "حذف المقال؟", en: "Delete this article?" },
  deleteBody: {
    ar: "يختفي من مركز المساعدة فوراً في التطبيق والموقع.",
    en: "It disappears from the help center in the app and on the web at once.",
  },
  cancel: { ar: "إلغاء", en: "Cancel" },
  saved: { ar: "حُفظ.", en: "Saved." },
  noArticles: { ar: "لا مقالات بعد.", en: "No articles yet." },
} as const satisfies Dictionary
